### ISSUE TITLE
MIM matrix conversion in plotting function 

### ISSUE THREAD

**Issue by fpellegrini** [arnodelorme/roiconnect#17]
This line https://github.com/arnodelorme/roiconnect/blob/c6ac8ded0d92402d069e676e318c572b018ff441/pop_roi_connectplot.m#L374
should be deleted since matrix conversion is now entirely handled by the roi_connect function 
(see here: https://github.com/arnodelorme/roiconnect/blob/c6ac8ded0d92402d069e676e318c572b018ff441/roi_connect.m#L99 
and here: https://github.com/arnodelorme/roiconnect/blob/c6ac8ded0d92402d069e676e318c572b018ff441/roi_connect.m#L105 and here: https://github.com/arnodelorme/roiconnect/blob/c6ac8ded0d92402d069e676e318c572b018ff441/roi_connect.m#L118.)

**Comment by arnodelorme** [comment]
Yes, I was confused because the code for get_connect_mat was gone but was still use at that location (so I added it back). It makes sense though, and I have removed it now. 3d947be
