### ISSUE TITLE
MIM/MIC labels

### ISSUE THREAD

**Issue by fpellegrini** [arnodelorme/roiconnect#6]
Here it should be 'Maximized Imaginary Coherency': 
https://github.com/arnodelorme/roiconnect/blob/0de6509af56e2c8257c7df267cfa51c0828fbf1a/pop_roi_connectplot.m#L135

and here 'Multivariate Interaction Measure': 
https://github.com/arnodelorme/roiconnect/blob/0de6509af56e2c8257c7df267cfa51c0828fbf1a/pop_roi_connectplot.m#L143

(and here: 
https://github.com/arnodelorme/roiconnect/blob/0de6509af56e2c8257c7df267cfa51c0828fbf1a/pop_roi_connectplot.m#L14
MIM and MIC are missing so far).

**Comment by arnodelorme** [comment]
Fixed them all
