### ISSUE TITLE
indexing bug

### ISSUE THREAD

**Issue by fpellegrini** [arnodelorme/roiconnect#7]
I think we have a bug here: 
https://github.com/arnodelorme/roiconnect/blob/ac9772522c6be5170ad2da8116a537bc14f8416a/roi_connect.m#L79-L80

Line 79 should be deleted, and then it is 
ninds = ninds + 1;  instead of ninds = ninds + 2;

Otherwise the 'unwrapping' from vector to matrix shape won't work correctly, see here: https://github.com/arnodelorme/roiconnect/blob/0de6509af56e2c8257c7df267cfa51c0828fbf1a/pop_roi_connectplot.m#L328
or also the previous post: https://github.com/arnodelorme/roiconnect/issues/5#issue-1114114887

**Comment by arnodelorme** [comment]
Fixed in ad82f2a
I have not tested though
