### ISSUE TITLE
number of principal components not modifyable

### ISSUE THREAD

**Issue by fpellegrini** [arnodelorme/roiconnect#8]
https://github.com/arnodelorme/roiconnect/blob/ac9772522c6be5170ad2da8116a537bc14f8416a/newscripts/process_ds001787.m#L80

Somehow, the nPCA parameter is always set to 3, no matter which input is given as key-value pair here. For example, if I enter 

...,'nPCA',1); 

the function still calculates with 3 components and outputs results accordingly. I'm currently not sure where exactly we can find the bug.

**Comment by arnodelorme** [comment]
Let me look into it
